@startuml

!define v8 https://raw.githubusercontent.com/nmnike/plantuml-lib/master/v8

!include v8/common.puml
!include v8/v8_Catalog.puml
!include v8/v8_Document.puml
!include v8/v8_InfoRg.puml
!include v8/v8_AccRg.puml

header Пример
title Пример диаграммы объектов 1С
right footer Группа технологической разработки

package ТМЦ <<Rectangle>> #LightYellow {

    _Справочник(Номенклатура){
        Ссылка
        Наименование
    }

    _Справочник(ВидыНоменклатуры, "Виды номенклатуры"){
        Ссылка
        Наименование
    }

    _Справочник(КлассыРентабельностиНоменклатуры, "Классы рентабельности номенклатуры"){
        Ссылка
    }
    
    _РегистрСведений(Ассортимент)

    _Документ(ПриобретениеТоваровУслуг, "Приобретение товаров и услуг")
    _Документ(ИзменениеАссортимента, "Изменение ассортимента")

    _РегистрНакопления(СвободныеОстатки, "Свободные остатки")

}

package Взаиморасчеты <<Rectangle>> #LightBlue {

    _Справочник(ДоговорыСКонтрагентами, "Договоры с контрагентами"){
        Ссылка
        Контрагент
    }
    
    _Справочник(Контрагенты){
        Ссылка
    }

}

ВидыНоменклатуры::Ссылка-->Номенклатура::Ссылка : Владелец
Номенклатура-->КлассыРентабельностиНоменклатуры
ДоговорыСКонтрагентами::Контрагент-->Контрагенты::Ссылка

ПриобретениеТоваровУслуг-down->СвободныеОстатки : "Приход"
ИзменениеАссортимента-down->Ассортимент

@enduml
